### ISSUE TITLE
Testing the pipeline on CPU, instead of GPU?

### ISSUE THREAD

**Issue by xxihe** [PYangLab/scDeepFeatures#1]
Hi,

I am interested in applying your pipeline on our own scRNA-seq data. However, our server only offers a CPU option. I am wondering is your pipeline can be tested on CPUs? Is it possible of you to provide an option to bypass the GPU setting? We just wanna have a quick test run on a small dataset to see the results. 

Best,
Xi

**Comment by Hao-Lawrence-Huang** [comment]
Thank you for your query. When running on a server without a GPU configuration, scDeepFeatures will automatically leverage the CPU. Hope this helps.
Cheers,

**Comment by xxihe** [comment]
Thank you for your reply!

When I am testing your example dataset on the server with CPU only, I got the error messages about missing GPU. Do you know why it did not switch to use the CPU automatically?

The error message:

Traceback (most recent call last):
  File "../scDeepFeatures/Utils/Feature_selection_methods/Mlp/main.py", line 41, in <module>
    "current device is: " + str(torch.cuda.get_device_name(0)))
  File "/storage/work/xuh142/miniconda/envs/fsdl/lib/python3.8/site-packages/torch/cuda/__init__.py", line 328, in get_device_name
    return get_device_properties(device).name
  File "/storage/work/xuh142/miniconda/envs/fsdl/lib/python3.8/site-packages/torch/cuda/__init__.py", line 358, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/storage/work/xuh142/miniconda/envs/fsdl/lib/python3.8/site-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

Best,
Xi

**Comment by Hao-Lawrence-Huang** [comment]
Hi Xi,

I have updated the print function and tested it on a CPU machine. Please try again and let me know how it goes.

Regards,
